supasate/connected-react-router

src/ConnectedRouter.js
=> Fix router.location is null on page load

src/ConnectedRouter.js
=> Handle changes of search and hash location in time travelling

examples/.babelrc, examples/package.json, examples/src/index.js, examples/webpack.config.js, examples/yarn.lock
Due to Webpack 2.2 stable is released, so, I changed the example to use the latest stable version.
=> Change example to use Webpack 2

.gitignore, package.json, webpack.config.js, yarn.lock
=> Add UMD build

package.json, yarn.lock
=> Update Redux peer dependency to Redux v4

README.md
=> fix 404 link to react router v4

README.md
react-hot-loader main branch is v4 now
=> Fix 404 react-hot-loader

immutable.d.ts, package.json, yarn.lock
=> improve typescript declaration files

immutable.d.ts, package.json
=> improve typescript declaration files and type dependency

index.d.ts
=> Fix connectRouter definition

package.json
=> Move history v4 to peer dependencies

src/ConnectedRouter.js, test/ConnectedRouter.test.js
=> Remove initial locationChanged action

src/ConnectedRouter.js, test/ConnectedRouter.test.js
Reverts supasate/connected-react-router#171
See #144.
=> Revert "Remove initial locationChanged action"

FAQ.md
In `FAQ.md`, add an example for push state using react-redux with connect
=> Add example for push state using react-redux with connect

src/immutable.js, src/seamless-immutable.js, src/selectors.js
Following up PR #203 by adding getHash and getSearch to immutable and seamless-immutable.
=> Support getHash and getSearch selectors for immutables

src/immutable.js, src/index.js, src/seamless-immutable.js
=> Export onLocationChanged action

README.md
Please feel free to reword or ignore as you see fit.  I thought this would be a good addition to an awesome library and hopefully help reduce some of instances of this error / confusion.
Thanks for all the great work!
=> Address part of the confusions highlighted in #230

src/ConnectedRouter.js
On this PR #363, I have an error when I try to run `eslint`.
=> fix(action): remove duplicate action key

FAQ.md, README.md
As requested #350, I updated the documentation for **react native** example.
=> Update FAQ for react native example

package.json, yarn.lock
=> Fix umd build command

package.json, yarn.lock
#399 causes a test failure as lodash.isequalwith is not listed in devDependencies.
=> Add lodash.isequalwith to devDependencies

package.json, yarn.lock
=> Move immutables to optional dependencies

package.json
As far as I can tell it's working without a problem
=> Update react peer dependency to include v17
