supasate/connected-react-router

- README.md
- examples/src/index.js
- examples/src/reducers/root.js
- src/ConnectedRouter.js
- src/index.js
- src/reducer.js
> Add connectRouter + example

- package.json
- yarn.lock
It is for Webpack, which we do not currently use in this repo.
> Remove unused devDependency `babel-loader`

- examples/webpack.config.js
Fix #17 
In examples folder, use `resolveLoader` to find `babel-loader` for local `connected-react-router` (for local development purpose)
> Fix module not found 'babel' for local development

- package.json
the latest stable version of react-redux is 5.0.2, which seems to work fine with this library to me.
> Also allow ^5.0.0 react-redux peer dependency

- examples/basic/package.json
- examples/basic/src/App.js
- examples/basic/src/components/Counter.js
- examples/basic/src/components/HelloChild.js
- examples/immutable/package.json
- examples/immutable/src/App.js
- examples/immutable/src/components/Counter.js
- examples/immutable/src/components/HelloChild.js
- package.json
- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
- yarn.lock
PropTypes were moved to a standalone package and enzyme now requires react-test-renderer/shallow.
> Upgrade to React 15.5 and React Router 4.1

- examples/typescript/src/reducers/index.ts
- index.d.ts
This allows you to do e.g.:
```ts
interface State {
count: number
router: RouterState
}
```
instead of
```ts
interface State {
count: number
router: {
location: {
pathname: string
search: string
hash: string
}
}
}
```
> Add RouterState to typings

- package.json
- src/ConnectedRouter.js
- src/reducer.js
- src/structure/immutable/getIn.js
- src/structure/immutable/setIn.js
- src/structure/plain/getIn.js
- src/structure/plain/setIn.js
- yarn.lock
This PR removes `lodash.topath` from the dependencies.
Removing it decreased my minified bundle size by ~5kB. That's not too significant of a reduction - but every byte helps, and this change also simplifies the code a bit.
Thanks!
> Remove `lodash.topath` dependency to reduce bundle size.

- package.json
Fixes #59 by adding `^react@^16.0.0` to the peerDependencies. `connected-react-router` itself works fine with `react@^16`.
> Update peerDependencies to include React 16

- package.json
- test/ConnectedRouter.test.js
- yarn.lock
Sort of follow up to #62, updates dependencies to match `react@^16.0.0`. All tests pass, but creates an additional warning for `redux-devtools` which doesn't have a version with `react@16` in peerDeps.
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>
> Update deps to match react@^16.0.0

- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
Dispatch a location change action for the initial location.
This allows code listening for the location change to be able to respond to the initial location in addition to subsequent location changes.
> dispatch location change action for initial location

- examples/typescript/package.json
- examples/typescript/yarn.lock
Typescipt example depends on connected-react-router v4.1.0, which does not support typescript yet.
This patch upgrade the dependency to v4.3.0 which supports typescript
> Fix typescript example is not compilable

- package.json
- yarn.lock
`react-router` should be treated as a peer dependency, so it's not bundled/required twice. Pretty much everyone using `connected-react-router` is also using `react-router`.
> Update react-router version and set as peerDependency

- src/createAll.js
- src/index.js
- src/selectors.js
- test/selectors.test.js
Hi and thanks for this library!
I'm migrating from [react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux) and the only thing that I'm really missing is its selectors... Specially the `createMatchSelector`. So, I have taken the ones from `react-router-redux` and I have migrated them (with their corresponding tests) so that they can work in this library.
I would really appreciate it if you could add them to `connected-react-router`.
> [FEAT]: Add selectors

- index.d.ts
This adds the RouterAction type originally from @types/react-router-redux
It allows type-safe dispatching like this:
```typescript
const mapDispatchToProps = (dispatch: Dispatch<UsersAction | RouterAction>) => ({
submit: (u: IUser) => {
dispatch(actionCreators.updateUser(u));
dispatch(push('/users'));
}
});
```
> add RouterAction to typings

- README.md
Closes #39 
Simply adds documentation on the main README file that specifies a link to a tutorial on how to implement server-side rendering, with a supporting codebase as an example.
> Fixes #39, adds support for server-side rendering in README

- index.d.ts
There are two "export RouterAction" which caused this tslint error, we should export those with different names.
> Rename RouterAction(enum) to prevent exported name collision

- src/immutable.js
- src/seamless-immutable.js
those functions weren't exported in immutable and seamlessImmutable
> getLocation, getAction, and createMatchSelector for immutable structures

- immutable.d.ts
- package.json
- yarn.lock
Reverts supasate/connected-react-router#134
I revert this because it may affect people who uses React 15.x. I'll merge this when we have a major upgrade.
> Revert "improve typescript declaration files"

- index.d.ts
Use the string literal `'@@router/CALL_HISTORY_METHOD'` as the type for `CALL_HISTORY_METHOD`.
I have a `type Action = LocationChangeAction | RouterAction` and would like to differentiate between types of actions using a switch statement like this:
```js
switch (action.type) {
case CALL_HISTORY_METHOD:
// x
case LOCATION_CHANGE:
// y
}
```
The type needs to be a string literal rather than a generic string type for this to work.
> Use string literal type for CALL_HISTORY_METHOD

- index.d.ts
If I do:
`const action = RouterActionType.PUSH;`
I get:
> Uncaught TypeError: Cannot read property 'PUSH' of undefined
So from my point it seems that RouterActionType shound not be an enum and a simple union if PUSH and POP instead.
Additionally it seems REPLACE is missing in RouterActionType.
> Typescript: change RouterActionType from enum to simple union cause enum seems wrong

- package.json
- yarn.lock
Move `redux-seamless-immutable` to `devDependencies`
- We use `redux-seamless-immutable` only for testing and It uses `react-router-redux` as its dependency which is no longer maintained.
resolve #164
> Move redux-seamless-immutable to devDependencies

- index.d.ts
Before this, the `RouterAction` type was just typed to have a `string` type, which would cause errors in a typescript application by making the compiler think every action was a `RouterAction` I have changed these types to be strongly typed on the exact strings of those actions.
> Updated action types.

- index.d.ts
I don't think it did any harm since it was merged with itself, but still.
> Remove a duplicate LocationChangeAction interface

- index.d.ts
Not sure if there was a reason for this, but all exposed action creators are known to return action with type `@@router/CALL_HISTORY_METHOD`, so the typings should reflect this, instead of being unambiguous about weather it's `@@router/LOCATION_CHANGE` or `@@router/CALL_HISTORY_METHOD`.
> Be more specific on action creators' return type

- FAQ.md
- README.md
- examples/basic/package.json
- examples/basic/yarn.lock
- examples/immutable/package.json
- examples/immutable/yarn.lock
- examples/typescript/package.json
- examples/typescript/yarn.lock
- package.json
- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
- yarn.lock
Fix #176 
Based on @wgao19's [fix](https://github.com/wgao19/connected-react-router/pull/1/files), this PR makes `ConnectedRouter` use the new Context API. We use `ReactReduxContext` as a default context and also support your own custom context by providing a `context` prop to both `<Provider>` and `<ConnectedRouter>`.
> Support React Router v6

- test/ConnectedRouter.test.js
Based on #208, add tests to make sure it works for immutable and seamless-immutable structure too.
And confirming that if we change it back to `Component` instead of `PureComponent`, it will fail the tests.
> Add double-rendering test for immutable and seamless-immutable

- src/ConnectedRouter.js
- src/actions.js
- src/reducer.js
- test/actions.test.js
- test/reducer.test.js
Based on #208, this PR adds `isFirstRendering` flag to indicate the first LOCATION_CHANGE action on initialization. So, the reducer can ignore it to prevent double-rendering. This should fix #193.
> Prevent double-rendering on initialization

- index.d.ts
- src/index.js
- src/selectors.js
- test/selectors.test.js
We can currently get the location and this action, this change adds the ability to retrieve the current search and hash.
> Create selectors to retrieve search and hash

- package.json
- src/ConnectedRouter.js
In #217, we move store and history subscription and the first `onLocationChange` call from `constructor` to `componentDidMount`. However, `react-router` subscribes `history` in `componentWillMount` (in 4.3.1) and `constructor` (in 4.4.0-beta). So, ConnectedRouter needs to subscribe to the store and history before `react-router`.
> Moving store and history subscription back to constructor

- index.d.ts
- package.json
- yarn.lock
- Add `@types/react-router` as devDependency
- Add typedef for root router state
- Add typedef for `getRouter`
- Add typedef for `createMatchSelector`
- Add typedef for router selectors to expect correct root state
Fixes #128
> Add missing typedef's for `getRouter` and `createMatchSelector`

- index.d.ts
The reason for this is to have better autocomplete on the created actions.
It seems like a very niche use, but I ran into it and would like to have better autocompletes.
Also improves the LocationState type inside LocationDescriptorObject, before it was aways `any`.
> Improving return types of action creators by adding generic args type

- index.d.ts
First of all, Thank you for maintaining an awesome library project :)
```
Type error: A parameter initializer is only allowed in a function or constructor implementation.  TS2371
62 |     S extends RouterRootState, Params extends { [K in keyof Params]?: string }
63 |   >(path: string): matchSelectorFn<S, Params>;
> 64 |   export function onLocationChanged(location: Location, action: RouterActionType, isFirstRendering: boolean = false)
|                                                                                   ^
65 |     : LocationChangeAction;
66 | 
67 |   export type Push = typeof push;
```
I've got this type error after bumping up dependency versions.
> Fix an invalid type definition

- webpack.config.js
If I use `eslint-plugin-import` in production, I get this error:
```
ERROR in ./src/javascripts/components/router/index.jsx
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
at Object.get [as UglifyJsPlugin] (/mnt/hot/w/shortcm/frontend/node_modules/webpack/lib/webpack.js:185:10)
at Object.<anonymous> (/mnt/hot/w/shortcm/frontend/node_modules/connected-react-router/webpack.config.js:18:26)
at Module._compile (/mnt/hot/w/shortcm/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
at Module._compile (/mnt/hot/w/shortcm/frontend/node_modules/pirates/lib/index.js:83:24)
at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
at Object.newLoader [as …
```
> Replace uglify option with new minimize options

- package.json
create-react-app when building with yarn, react 16
```
$ react-scripts start
Starting the development server...
Failed to compile.
/usr/local/share/.cache/yarn/v4/npm-connected-react-router-5.0.1-8379854fad7e027b1e27652c00ad534f8ad244b3/node_modules/connected-react-router/lib/ConnectedRouter.js
Module not found: Package "connected-react-router@5.0.1" (via "/usr/local/share/.cache/yarn/v4/npm-connected-react-router-5.0.1-8379854fad7e027b1e27652c00ad534f8ad244b3/node_modules/connected-react-router/lib/ConnectedRouter.js") is trying to require the package "prop-types" (via "prop-types") without it being listed in its dependencies (history, react, react-redux, react-router, redux, immutable, seamless-immutable, connected-react-router)
```
> prop-types: declare as a peer dependency

- index.d.ts
The RouterState interface does not have the isFirstRendering property.
This PR is for adding the isFirstRendering property to the RouterState interface.
> add isFirstRendering property to RouterState interface

- examples/typescript/src/App.tsx
Hello ~ 
```js
import {History} from 'history'
```
I think this code violate code rule compared to other codes
so i changed this a little 0_<
```js
import { History } from 'history'
```
> Fix code rule example/typescript/src/App.tsx

- FAQ.md
- README.md
- package.json
- yarn.lock
This updates the `package.json` file to add compatibility with [react-router@`^5.0.0`](https://github.com/ReactTraining/react-router/releases/tag/v5.0.0). Even though the major version of `react-router` changed, it is fully backwards compatible:
> Despite the major bump, this is actually a minor release. It is fully backwards compatible with any project coming from 4.x. Sorry for the convenience. :grimacing:
-- https://github.com/ReactTraining/react-router/releases/tag/v5.0.0
Further information: https://github.com/ReactTraining/react-router/issues/6643
> Add support for react-router@5.0.0

- package.json
- yarn.lock
[A recent PR (#265)](https://github.com/supasate/connected-react-router/pull/265) added `prop-types` to `peerDependencies`. I'm afraid that's not quite the right way to do it, because the official `prop-types` documentation states:
> For libraries, we also recommend leaving it in dependencies:
```
"dependencies": {
"prop-types": "^15.5.7"
},
"peerDependencies": {
"react": "^15.5.0"
}
```
-- https://github.com/facebook/prop-types#how-to-depend-on-this-package
I use `connected-react-router` in a Typescript project and don't need `prop-types`, but because it is a `peer-dependency` I receive a "missing peer dependency warning" when installing this package.
This PR therefore removes `prop-types` from both `peerDependencies` and `devDependencies`.
> Move prop-types from peerDependencies into dependencies

- README.md
There is already a `How to implement server-side rendering` link to a very nice article. However, we should still be explicit regarding not to use `ConnectedRouter` on server-side.
Indeed, in one of our applications, we happen to be running with  the `ConnectedRouter` on server-side and it was running fine. However, after updating `react-redux` to `7.1` (from `7.0`), the app was starting to break. This was due to the fact that we were using the `context` prop like the `staticContext` prop of `StaticRouter` 😬 Of course, all our logic using the `StaticContext` was also silently breaking ^^
> Add a more explicit note on SSR

- src/reducer.js
- test/reducer.test.js
- test/selectors.test.js
This pull request adds the `query` object to `location`. This is useful when a user needs to access the value(s) in the search/query string without having to parse the search string themself.
> Injected query into location

- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
> Include location state in LOCATION_CHANGE payload

- package.json
- yarn.lock
The original discussion: #296
Currently, I use `connected-react-router`, `redux-form` and the project doesn't depend on `immutable` at all. But it seems like `redux-form` is pretty eager for `immutable` library and if it presents inside `node_modules` it will be included in the bundle, which is pretty confusing. I'm not sure what was the purpose to include `immutable` and `seamless-immutable` in the library dependencies (keeping in mind that redux and react-router related stuff lives in `peerDependencies`), so these are breaking changes. Anyway everyone who wants `immutable` or `seamless-immutable` version of this package already has these packages installed, so it won't be a big issue for them to migrate.
> Move immutable and seamless-immutable to peer dependencies

- FAQ.md
- index.d.ts
- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
Makes the logic added back in https://github.com/supasate/connected-react-router/pull/172/files optional
Can be called like
```jsx
<ConnectedRouter history={history} noInitialPop>
```
Discussed in https://github.com/supasate/connected-react-router/issues/144
> Make initial location POP optional

- src/reducer.js
- test/reducer.test.js
When using ConnectedRouter you may have already set a query with a custom parser like this
```jsx
const history = qhistory(createBrowserHistory(), stringify, parseQueryString);
<ConnectedRouter history={history}>
```
This PR ensures it doesn't override existing queries which may have different parsing logic
Ive published this under https://www.npmjs.com/package/@dr3/connected-react-router for the meantime :)
> Disable query injection when key exists already

- src/selectors.js
- test/selectors.test.js
In situation when url matched for nested routes, url is always the same but isExact is not.
> lastMatch should depend on isExact as well

- package.json
- src/ConnectedRouter.js
- test/ConnectedRouter.test.js
- yarn.lock
Closes #394. This change deep compares location state objects to prevent incorrectly pushing to history multiple times when state is changed.
> Fix location state (#394)

- index.d.ts
Find same question as #381 
`index.d.ts` file miss type definition for query in RouterState.location.
> Add query type definition for RouterState.location #381

- src/immutable.js
- src/index.js
- src/seamless-immutable.js
Fixes #427:
The types file lists `getRouter()` as being available:
https://github.com/supasate/connected-react-router/blob/f27512640e992f420935c7790cdbed746a8306e0/index.d.ts#L68
It's returned from `createSelectors()`:
https://github.com/supasate/connected-react-router/blob/adc65f8d55dfde0f4db7609c72c723ce62698917/src/selectors.js#L49-L56
but is not actually exported from the package:
https://github.com/supasate/connected-react-router/blob/e444615c281bcb4d518636bee2666d1e9357bf8e/src/index.js#L11
https://github.com/supasate/connected-react-router/blob/e444615c281bcb4d518636bee2666d1e9357bf8e/src/immutable.js#L11
https://github.com/supasate/connected-react-router/blob/e444615c281bcb4d518636bee2666d1e9357bf8e/src/seamless-immutable.js#L11
This PR rectifies this by adding `getRouter` to the …
> Fix: Export getRouter() selector

- index.d.ts
- package.json
- src/ConnectedRouter.js
This allows for the following configuration:
Currently, my team is running into this situation where `Router` is provided at a higher point in the architecture and we want to use `connected-react-router` with our Redux store, but we need `connected-react-router` to use the `Router` instance that is higher up the tree instead of providing its own.
This option is added as opt-in only and should not affect any existing usage.
> Add "omitRouter" option

- index.d.ts
`path` parameter should match parameter of the underlying `matchPath`
fix #258
> update createMatchSelector parameter typing

- index.d.ts
- src/ConnectedRouter.js
Allow time travel debugging compatibility to be turned off as the detection for this is error prone in apps where the store may be unmounted, a navigation occurs, and then the store is re-mounted during the app's lifetime. Detection could be much improved if Redux DevTools simply set a global variable like `REDUX_DEVTOOLS_IS_TIME_TRAVELLING=true`.
> noTimeTravelDebugging prop

- index.d.ts
Current typing definition will cause the following error when upgrading to React 18 typing definitions
Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes ...
This PR adds the children prop.
Ref: https://github.com/supasate/connected-react-router/issues/565
See also SO answer as reference:
https://stackoverflow.com/questions/71788254/react-18-typescript-children-fc/71809927#71809927
> add children to typings to support removal of same in react 18 typings
